### ISSUE TITLE
question about the weight loss

### ISSUE THREAD

**Issue by Wangt-CN** [mratsim/Amazon_Forest_Computer_Vision#2]
Thankyou for your great code!
Recently I am solving a problem about multilabel classify.And i have more lable(500) and is binary and one hot，but the 0 is more than 1, maybe about 50 times?
And i notice that you have use  the weight loss and seem that the weight is relevent to the frequency?
Can you give me more details or ideas?
Thankyou   best regards!

**Comment by codeXiaoLi** [comment]
> Thankyou for your great code!
> Recently I am solving a problem about multilabel classify.And i have more lable(500) and is binary and one hot，but the 0 is more than 1, maybe about 50 times?
> And i notice that you have use the weight loss and seem that the weight is relevent to the frequency?
> Can you give me more details or ideas?
> Thankyou best regards!

hello, i am doing a task of multilabel classification, may i have your wechat to chat with you about the problem of unbalanced data?  Thank you, i am master candidate.

**Comment by mratsim** [comment]
@Wangt-CN Sorry for replying more than a year later.

The idea was to give more weight to examples that are seen less otherwise in the extreme case say 99 true and 1 false, the network would have 100% accuracy by always predicting true.

In your case, since 2017/2018 there might have been several advances in anomaly detection techniques that should be even better than simple weight changes.
